language: ruby
rvm:
  - 2.4.4
env:
  - DB=mysql
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate spec
before_script:
  - mysql -e 'create database gera_test'
  - psql -c 'create database gera_test' -U postgres
services:
  - mysql
  - postgresql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

sudo: required
