language: ruby
cache: bundler
env:
  - DB=mysql
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake --trace spec
before_script:
  - cat ~travis/.my.cnf
  - RAILS_ENV=test bundle exec rake --trace db:create db:migrate
services:
  - postgresql
  - mysql
dist: xenial
sudo: required
